// Centralized content for the public Accident Compensation Helper website.
// All photography is generated and stored with the app (media.base44.com).

export const IMAGES = {
  hero: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/f5d909a06_generated_image.png",
  attorneyConsultation: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/d77e25e69_generated_image.png",
  car: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/235ce8e0f_generated_image.png",
  truck: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/b3d5fb79a_generated_image.png",
  motorcycle: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/5361a35ed_generated_image.png",
  rideshare: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/bca234ce8_generated_image.png",
  pedestrian: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/d387e4d2b_generated_image.png",
  workplace: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/ef8e4f00c_generated_image.png",
  slipfall: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/6218c50b4_generated_image.png",
  other: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/3d1fc69d5_generated_image.png",
  recovery: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/51f3489ef_generated_image.png",
  claimCheck: "https://media.base44.com/images/public/6a9667f0d469f05277f69ab4/de8150c47_generated_image.png",
};

export const NAV_LINKS = [
  { label: "Home", to: "/" },
  { label: "How It Works", to: "/how-it-works" },
  { label: "Accident Types", to: "/accident-types" },
  { label: "Resources", to: "/resources" },
  { label: "About", to: "/about" },
  { label: "FAQ", to: "/faq" },
  { label: "Contact", to: "/contact" },
];

// Maps the claim engine accident_type id to an accident-type page slug.
export const ACCIDENT_TYPE_BY_ID = {
  "Auto Accident": "car-accidents",
  "Commercial Accident": "truck-accidents",
  "Rideshare Accident": "rideshare-accidents",
  "Workplace Accident": "workplace-accidents",
  "Slip and Fall": "slip-and-fall",
  "Medical Malpractice": "other-personal-injury",
};

export const ACCIDENT_TYPES = [
  {
    slug: "car-accidents",
    label: "Car Accidents",
    claimId: "Auto Accident",
    image: IMAGES.car,
    short: "Rear-end, intersection, and highway collisions involving passenger vehicles.",
    intro: "Car accidents are among the most common sources of personal injury claims. Even a collision that looks minor can cause injuries that take days or weeks to appear. Understanding how insurance evaluates a car accident can help you decide whether a conversation with a participating attorney may be useful.",
    causes: [
      "Distracted or impaired driving",
      "Failure to yield or running a red light",
      "Following too closely (rear-end collisions)",
      "Unsafe lane changes and speeding",
      "Poor weather or road conditions",
    ],
    injuries: [
      "Whiplash and neck injuries",
      "Back and spinal injuries",
      "Concussions and head injuries",
      "Cuts, bruises, and soft-tissue injuries",
    ],
    evidence: [
      "Photos of vehicle damage and the scene",
      "The police or crash report",
      "Medical records and bills",
      "Witness contact information",
    ],
    insurance: "Most drivers carry liability coverage, but policy limits and comparative-fault rules vary by state. An insurer may offer a quick settlement before the full extent of injuries is known.",
    faq: [
      { q: "Should I see a doctor if I feel fine after a crash?", a: "Many injuries, including whiplash and concussions, may not be noticeable immediately. A prompt medical evaluation creates a record of your condition and can identify injuries early." },
      { q: "The insurer offered a quick settlement. What should I do?", a: "A fast offer may not account for ongoing treatment or future costs. Understanding the full scope of your injuries before signing anything is often advisable. A participating attorney can review the offer." },
      { q: "Can I still pursue a claim if I was partly at fault?", a: "Many states apply comparative-fault rules that may reduce, but not always eliminate, recovery. How this applies depends on your state and the facts of the collision." },
    ],
    metaTitle: "Car Accident Claims: What to Know | Accident Compensation Helper",
    metaDescription: "Learn how car accident claims work, common injuries, useful evidence, and insurance considerations. Start a free, confidential claim check in about two minutes.",
  },
  {
    slug: "truck-accidents",
    label: "Truck Accidents",
    claimId: "Commercial Accident",
    image: IMAGES.truck,
    short: "Collisions involving commercial trucks, delivery vehicles, and tractor-trailers.",
    intro: "Commercial truck claims can be more complex than passenger-vehicle claims because multiple parties may be involved, including the driver, the carrier, and the shipper. Federal and state regulations may also apply.",
    causes: [
      "Driver fatigue and long hours",
      "Improperly loaded or overloaded cargo",
      "Inadequate vehicle maintenance",
      "Distracted or impaired driving",
      "Insufficient driver training",
    ],
    injuries: [
      "Severe trauma due to the size and weight of trucks",
      "Spinal and head injuries",
      "Fractures and crush injuries",
      "Long-term or permanent impairment",
    ],
    evidence: [
      "The truck driver's logbook and records",
      "Vehicle maintenance and inspection records",
      "Electronic data from the truck's systems",
      "Scene photos and the police report",
    ],
    insurance: "Commercial carriers typically carry larger policies, but identifying the responsible party and the applicable coverage can be complicated. Multiple insurers may be involved.",
    faq: [
      { q: "Why are truck accident claims different from car claims?", a: "Truck claims often involve multiple parties, commercial insurance policies, and federal safety regulations. This can make identifying responsibility and coverage more involved." },
      { q: "Who may be responsible for a truck accident?", a: "Depending on the facts, the driver, the trucking company, a cargo loader, or a vehicle manufacturer may share responsibility. A participating attorney can help review the parties involved." },
      { q: "What records can help a truck claim?", a: "Driver logbooks, maintenance records, and electronic data from the truck can be important. These records may not be preserved indefinitely." },
    ],
    metaTitle: "Truck Accident Claims: What to Know | Accident Compensation Helper",
    metaDescription: "Commercial truck claims involve multiple parties and regulations. Learn common causes, injuries, evidence, and insurance considerations before you decide your next step.",
  },
  {
    slug: "motorcycle-accidents",
    label: "Motorcycle Accidents",
    claimId: "Auto Accident",
    image: IMAGES.motorcycle,
    short: "Collisions involving motorcyclists, who often face more severe injuries.",
    intro: "Motorcyclists have little physical protection, so injuries tend to be serious. Insurance companies may also hold biases about motorcyclists, which can affect how a claim is evaluated.",
    causes: [
      "Drivers failing to see motorcyclists",
      "Unsafe lane changes and door openings",
      "Speeding and impaired riding",
      "Road hazards such as potholes and debris",
    ],
    injuries: [
      "Road rash and severe soft-tissue injuries",
      "Head and brain injuries",
      "Fractures and joint damage",
      "Spinal injuries",
    ],
    evidence: [
      "Helmet and protective-gear condition",
      "Photos of the scene and road conditions",
      "The police report and witness statements",
      "Medical records documenting injuries",
    ],
    insurance: "Motorcycle coverage and the at-fault driver's liability coverage both may apply. Bias about motorcyclists can influence how insurers value a claim.",
    faq: [
      { q: "Does wearing a helmet affect a claim?", a: "Helmet use can be relevant to the severity of head injuries. Some states have helmet laws that may also be a factor. Not wearing a helmet does not automatically prevent a claim." },
      { q: "Are motorcycle claims harder to resolve?", a: "They can be, because injuries are often serious and insurers may apply bias. Documenting the scene and injuries thoroughly can help." },
      { q: "What if the other driver says they didn't see me?", a: "Failure to see a motorcyclist does not necessarily remove responsibility. The facts of the collision and right-of-way rules still apply." },
    ],
    metaTitle: "Motorcycle Accident Claims: What to Know | Accident Compensation Helper",
    metaDescription: "Motorcycle accidents often cause serious injuries. Learn common causes, evidence that helps, and insurance considerations. Start a free, confidential claim check.",
  },
  {
    slug: "rideshare-accidents",
    label: "Rideshare Accidents",
    claimId: "Rideshare Accident",
    image: IMAGES.rideshare,
    short: "Accidents involving Uber, Lyft, and other rideshare or gig drivers.",
    intro: "Rideshare accidents can raise questions about which insurance policy applies, because coverage may depend on whether a driver was waiting for a ride, en route, or carrying a passenger.",
    causes: [
      "Distracted driving while using the rideshare app",
      "Fatigue from long hours",
      "Speeding to meet pickup or drop-off times",
      "Unfamiliar routes and sudden stops",
    ],
    injuries: [
      "Whiplash and neck injuries",
      "Head and back injuries",
      "Fractures and soft-tissue injuries",
    ],
    evidence: [
      "The rideshare driver's app status at the time",
      "Photos of the scene and vehicle damage",
      "The police report",
      "Medical records",
    ],
    insurance: "Rideshare companies provide contingent coverage that may apply depending on the driver's app status. The driver's personal auto policy and the at-fault party's coverage may also be involved.",
    faq: [
      { q: "Whose insurance applies in a rideshare accident?", a: "It depends on the driver's app status, the rideshare company's contingent coverage, and the at-fault party. Multiple policies may be involved." },
      { q: "I was a passenger in a rideshare. Can I make a claim?", a: "Passengers may be able to pursue a claim against the responsible party or applicable coverage. The facts of the collision determine the options." },
      { q: "Does the rideshare company cover me directly?", a: "Rideshare companies typically provide contingent commercial coverage that may apply in certain circumstances. Coverage depends on the driver's status and the policy terms." },
    ],
    metaTitle: "Rideshare Accident Claims: What to Know | Accident Compensation Helper",
    metaDescription: "Rideshare accidents involve layered insurance coverage. Learn how app status affects claims, common injuries, and evidence. Start a free claim check.",
  },
  {
    slug: "pedestrian-bicycle-accidents",
    label: "Pedestrian and Bicycle Accidents",
    claimId: "Other",
    image: IMAGES.pedestrian,
    short: "Collisions where a vehicle strikes someone walking, running, or cycling.",
    intro: "Pedestrians and cyclists have no physical protection, so injuries are often serious. These claims can involve right-of-way rules and questions about visibility and driver attention.",
    causes: [
      "Failure to yield at crosswalks and intersections",
      "Distracted or impaired driving",
      "Speeding in pedestrian-heavy areas",
      "Dooring of cyclists",
    ],
    injuries: [
      "Head and brain injuries",
      "Fractures and road injuries",
      "Spinal injuries",
      "Long-term mobility limitations",
    ],
    evidence: [
      "Photos of the crosswalk, signals, and scene",
      "Witness statements",
      "The police report",
      "Medical records",
    ],
    insurance: "The driver's liability coverage generally applies. In some cases, the injured person's own auto or health coverage may also play a role.",
    faq: [
      { q: "I was crossing outside a crosswalk. Can I still have a claim?", a: "Possibly. Right-of-way rules and comparative-fault principles vary by state. The facts of the incident determine what options may be available." },
      { q: "What if the driver fled the scene?", a: "A hit-and-run can complicate a claim, but uninsured motorist coverage or other options may apply. Reporting the incident to police is important." },
      { q: "Does wearing a helmet matter for cyclists?", a: "Helmet use can be relevant to head injury severity. Some jurisdictions have helmet requirements. Not wearing a helmet does not automatically prevent a claim." },
    ],
    metaTitle: "Pedestrian and Bicycle Accident Claims | Accident Compensation Helper",
    metaDescription: "Pedestrian and cyclist injuries are often serious. Learn common causes, evidence that helps, and insurance considerations. Start a free claim check.",
  },
  {
    slug: "workplace-accidents",
    label: "Workplace Accidents",
    claimId: "Workplace Accident",
    image: IMAGES.workplace,
    short: "On-the-job injuries across construction, industrial, warehouse, and office settings.",
    intro: "Workplace injuries are often handled through workers' compensation, but a third-party claim may also be available when someone other than the employer contributed to the injury. Understanding both paths can matter.",
    causes: [
      "Falls from heights and same-level slips",
      "Equipment and machinery accidents",
      "Repetitive-strain injuries",
      "Being struck by objects or vehicles",
    ],
    injuries: [
      "Back and joint injuries",
      "Fractures and crush injuries",
      "Head and eye injuries",
      "Occupational illness and repetitive-strain conditions",
    ],
    evidence: [
      "Incident reports and employer records",
      "Photos of the scene and equipment",
      "Witness statements",
      "Medical and treatment records",
    ],
    insurance: "Workers' compensation generally applies regardless of fault, but a separate third-party claim may be available when a contractor, equipment maker, or other party contributed.",
    faq: [
      { q: "Can I sue my employer for a workplace injury?", a: "In most cases, workers' compensation is the primary remedy against an employer. A third-party claim against another responsible party may be separate." },
      { q: "What is a third-party claim?", a: "A third-party claim is a separate claim against someone other than the employer who contributed to the injury, such as a contractor or equipment manufacturer." },
      { q: "Do I need to report the injury right away?", a: "Prompt reporting helps preserve evidence and meet workers' compensation deadlines. Waiting can complicate a claim." },
    ],
    metaTitle: "Workplace Accident Claims: What to Know | Accident Compensation Helper",
    metaDescription: "Workplace injuries may involve workers' compensation and sometimes a third-party claim. Learn common causes, evidence, and next steps. Start a free claim check.",
  },
  {
    slug: "slip-and-fall",
    label: "Slip and Fall Accidents",
    claimId: "Slip and Fall",
    image: IMAGES.slipfall,
    short: "Injuries from slips, trips, and falls on someone else's property.",
    intro: "Slip-and-fall claims are a type of premises liability case. They often turn on whether the property owner knew or should have known about the hazardous condition and failed to address it.",
    causes: [
      "Wet or recently cleaned floors without warning",
      "Uneven surfaces, loose carpet, or broken steps",
      "Poor lighting in walkways and stairwells",
      "Ice and snow that was not cleared",
    ],
    injuries: [
      "Hip and wrist fractures",
      "Head and back injuries",
      "Soft-tissue and sprain injuries",
      "Injuries aggravated by age or prior conditions",
    ],
    evidence: [
      "Photos of the hazard and surrounding area",
      "Incident reports from the property",
      "Witness statements",
      "Medical records",
    ],
    insurance: "The property owner's liability coverage generally applies. Notice of the hazard and the injured person's own care may affect the claim.",
    faq: [
      { q: "The store says it wasn't their fault. What now?", a: "Premises claims often depend on whether the owner knew or should have known about the hazard. Evidence of how long the condition existed can be important." },
      { q: "I fell but didn't report it immediately. Can I still claim?", a: "Reporting delays can complicate a claim but do not automatically prevent one. Documenting the scene and seeking medical care promptly helps." },
      { q: "Does my own carelessness matter?", a: "Comparative-fault rules may reduce recovery based on the injured person's own conduct. How this applies depends on your state." },
    ],
    metaTitle: "Slip and Fall Claims: What to Know | Accident Compensation Helper",
    metaDescription: "Slip-and-fall claims are premises liability cases. Learn what makes them stronger, common injuries, and evidence that helps. Start a free claim check.",
  },
  {
    slug: "other-personal-injury",
    label: "Other Personal Injury Claims",
    claimId: "Other",
    image: IMAGES.other,
    short: "Other injury situations, including medical malpractice and product injuries.",
    intro: "Not every injury fits a single category. Other personal injury claims can include medical malpractice, defective products, dog bites, and other situations where someone's carelessness may have caused harm.",
    causes: [
      "Negligent professional care",
      "Defective or dangerous products",
      "Animal bites or attacks",
      "Assault or other intentional acts",
    ],
    injuries: [
      "Varies widely depending on the situation",
      "Physical injuries and resulting treatment needs",
      "Ongoing pain and limitations",
    ],
    evidence: [
      "Medical and treatment records",
      "Product documentation and receipts",
      "Photos and incident reports",
      "Expert evaluation where relevant",
    ],
    insurance: "Coverage depends on the type of claim. Professional liability, product liability, and general liability policies may each apply differently.",
    faq: [
      { q: "How do I know if my situation qualifies?", a: "The claim check asks about what happened, your injuries, and treatment. It provides an informational assessment of whether further review may be useful." },
      { q: "Is medical malpractice the same as a normal injury claim?", a: "Medical malpractice claims often have special rules, expert requirements, and shorter deadlines. A participating attorney can help evaluate the specifics." },
      { q: "What if I'm not sure what category my injury falls into?", a: "You can select 'Other' in the claim check. The questions help organize the important details regardless of category." },
    ],
    metaTitle: "Other Personal Injury Claims | Accident Compensation Helper",
    metaDescription: "Not every injury fits one category. Learn about other personal injury claims, including malpractice and product injuries. Start a free claim check.",
  },
];

export const RESOURCE_CATEGORIES = [
  "After an Accident",
  "Insurance Claims",
  "Medical Treatment",
  "Compensation Basics",
  "Attorney Questions",
  "State Deadlines",
  "Evidence and Documentation",
];

export const RESOURCES = [
  {
    slug: "what-to-do-after-a-car-accident",
    title: "What to Do After a Car Accident",
    category: "After an Accident",
    excerpt: "A practical, step-by-step guide to the moments and days after a collision, focused on safety, documentation, and protecting your options.",
    metaTitle: "What to Do After a Car Accident: A Step-by-Step Guide",
    metaDescription: "A practical guide to what to do after a car accident, from staying safe at the scene to documenting injuries and protecting your options.",
    body: `## At the scene\n\nThe first priority is safety. If anyone is injured, call for medical help. Move vehicles out of traffic if it is safe to do so, and turn on hazard lights.\n\nIf you are able, gather basic information: the other driver's name, contact details, and insurance information, along with the license plate and a description of the vehicles. Take photographs of vehicle damage, the road, traffic controls, and any visible injuries.\n\n## In the days that follow\n\nSome injuries, including whiplash and concussions, may not be apparent immediately. Seeing a doctor promptly creates a record of your condition and can identify injuries early. Keep copies of medical records, bills, and receipts.\n\nAvoid discussing fault in detail with the other driver's insurer before you understand the full extent of your injuries. A quick settlement may not account for ongoing treatment.\n\n## Organizing the details\n\nWrite down what you remember while it is fresh. Note the date, time, weather, road conditions, and the sequence of events. Keep all documents in one place so they are easy to find later.\n\nIf you are unsure whether your situation may be worth reviewing, a free claim check can help organize the important details and indicate whether speaking with a participating attorney may be useful.\n\n> This article is general information and is not legal advice. A licensed attorney can advise you about your particular circumstances.`,
  },
  {
    slug: "what-information-to-collect-after-a-crash",
    title: "What Information Should I Collect After a Crash?",
    category: "Evidence and Documentation",
    excerpt: "The details you gather at the scene and afterward can shape how a claim is evaluated. Here is what to collect and why it matters.",
    metaTitle: "What Information to Collect After a Crash",
    metaDescription: "A checklist of the information and evidence that can help after a car accident, from driver details to medical records.",
    body: `## At the scene\n\n- The other driver's name, contact details, and insurance information\n- Vehicle descriptions and license plate numbers\n- Photos of vehicle damage, the road, and traffic controls\n- Contact information for any witnesses\n- The police or crash report number\n\n## Medical and financial records\n\n- Medical records and treatment notes\n- Bills and receipts for treatment, medication, and travel\n- Pay records showing time off work\n- Repair estimates and vehicle-related costs\n\n## Your own notes\n\n- A written account of what happened, while memory is fresh\n- The date, time, weather, and road conditions\n- How you felt in the days after the crash\n\nKeeping these details organized makes it easier to understand the full picture of what happened and how the accident affected you.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "when-to-seek-medical-treatment",
    title: "When Should I Seek Medical Treatment?",
    category: "Medical Treatment",
    excerpt: "Prompt medical care protects your health and creates a record of your injuries. Here is why timing matters.",
    metaTitle: "When Should I Seek Medical Treatment After an Accident?",
    metaDescription: "Why prompt medical evaluation matters after an accident, even when injuries seem minor, and how it affects a claim.",
    body: `## Some injuries are not obvious right away\n\nAdrenaline can mask pain in the moments after a crash. Whiplash, concussions, and soft-tissue injuries may appear hours or days later. A prompt medical evaluation can identify injuries before they worsen.\n\n## Treatment creates a record\n\nMedical records connect your injuries to the accident. A gap between the crash and your first treatment can make it harder to show that the injuries were caused by the collision.\n\n## Follow your treatment plan\n\nFollowing medical advice and attending follow-up appointments supports both your recovery and the documentation of your condition. Keep records of every visit.\n\n## When to go to the emergency room\n\nSeek emergency care for severe pain, head injury, loss of consciousness, numbness, or any sign of a serious condition. When in doubt, it is reasonable to be evaluated.\n\n> This article is general information and is not a substitute for medical or legal advice.`,
  },
  {
    slug: "how-insurance-companies-evaluate-injury-claims",
    title: "How Insurance Companies Evaluate Injury Claims",
    category: "Insurance Claims",
    excerpt: "Understanding how insurers value a claim can help you make informed decisions about settlement offers.",
    metaTitle: "How Insurance Companies Evaluate Injury Claims",
    metaDescription: "An overview of how insurers assess injury claims, including damages, evidence, and the role of fault.",
    body: `## What insurers look at\n\nAdjusters generally consider the severity of injuries, the cost of treatment, lost income, the clarity of fault, and the strength of the evidence. Policy limits also affect what is available.\n\n## Economic and non-economic damages\n\nEconomic damages include medical bills and lost wages. Non-economic damages, such as pain and suffering, are harder to measure and are often negotiated.\n\n## The role of fault\n\nIn states that apply comparative fault, the amount you may recover can be reduced by your share of responsibility. Clear evidence of the other party's fault can strengthen a claim.\n\n## Early settlement offers\n\nA quick offer may be made before the full extent of injuries is known. Understanding the complete picture of your treatment and costs before accepting can be important.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "what-is-a-contingency-fee",
    title: "What Is a Contingency Fee?",
    category: "Attorney Questions",
    excerpt: "A contingency fee is a common arrangement in personal injury cases. Here is how it typically works.",
    metaTitle: "What Is a Contingency Fee? How It Works",
    metaDescription: "An explanation of contingency-fee arrangements in personal injury cases and what to confirm with an attorney.",
    body: `## The basic idea\n\nUnder a contingency-fee arrangement, the attorney's fee is based on the amount recovered. If there is no recovery, the attorney typically does not charge a fee, though the client may still be responsible for costs.\n\n## Fee percentages vary\n\nThe percentage and how it is calculated can vary. Some agreements apply the percentage before costs are deducted and some after. These terms should be confirmed in writing.\n\n## Costs are separate\n\nCosts such as filing fees, expert witnesses, and records fees may be separate from the attorney's fee. Ask how costs are handled whether or not the case is successful.\n\n## Confirm the terms directly\n\nFee terms, costs, and responsibilities vary by attorney and by case. Any fee agreement is between you and the attorney and should be reviewed carefully before signing.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "what-does-no-win-no-fee-mean",
    title: 'What Does "No Win, No Fee" Usually Mean?',
    category: "Attorney Questions",
    excerpt: "The phrase is common in advertising. Here is what it generally refers to and what to ask about.",
    metaTitle: 'What Does "No Win, No Fee" Mean?',
    metaDescription: "What 'no win, no fee' usually refers to in personal injury cases and the questions worth asking before agreeing.",
    body: `## A common shorthand\n\n"No win, no fee" is a common way of describing a contingency-fee arrangement, where the attorney's fee depends on a recovery being obtained.\n\n## It is not the whole picture\n\nThe phrase does not always address costs, which may be separate from the fee. It also does not guarantee a particular outcome or amount.\n\n## Questions worth asking\n\n- What percentage does the attorney charge, and how is it calculated?\n- Are costs deducted before or after the fee is calculated?\n- Am I responsible for costs if there is no recovery?\n- What happens if the case does not resolve in my favor?\n\n## Confirm in writing\n\nAny arrangement should be set out clearly in a written fee agreement that you understand before signing.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "what-happens-during-an-attorney-consultation",
    title: "What Happens During an Attorney Consultation?",
    category: "Attorney Questions",
    excerpt: "Knowing what to expect can make a first conversation with an attorney less intimidating.",
    metaTitle: "What Happens During an Attorney Consultation",
    metaDescription: "What to expect during a first consultation with a personal injury attorney and how to prepare.",
    body: `## The purpose of a consultation\n\nA consultation is an initial conversation in which the attorney learns about your situation and you learn about how they may be able to help. It does not by itself create an attorney-client relationship.\n\n## What the attorney may ask\n\n- What happened, in your own words\n- Your injuries and treatment\n- The documents and evidence you have\n- Your goals and concerns\n\n## What you may ask\n\n- How does the attorney's fee structure work?\n- What is the likely process and timeline?\n- Who will handle the day-to-day work on the matter?\n- What are the next steps?\n\n## Preparing can help\n\nBring a summary of what happened, a list of your medical providers, and copies of key documents can make the conversation more productive.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "claim-if-partly-at-fault",
    title: "Can I Still Have a Claim If I Was Partly at Fault?",
    category: "Compensation Basics",
    excerpt: "Comparative and contributory fault rules vary by state. Here is what to understand.",
    metaTitle: "Can I Have a Claim If I Was Partly at Fault?",
    metaDescription: "How comparative and contributory fault rules can affect a personal injury claim when you share responsibility.",
    body: `## Fault is not always all-or-nothing\n\nMany states apply comparative-fault rules. Under these rules, the amount you may recover can be reduced by your share of responsibility, and in some states you may be barred if your share exceeds a certain threshold.\n\n## Two common approaches\n\n- **Pure comparative fault:** Your recovery is reduced by your percentage of fault, even if it is high.\n- **Modified comparative fault:** You may recover only if your fault is below a set threshold, often 50% or 51%.\n\n## A few states use contributory fault\n\nIn a small number of states, sharing any fault may bar recovery. These rules are strict and make the facts of fault especially important.\n\n## Why the details matter\n\nHow fault is assigned can significantly affect a claim. A participating attorney can help evaluate how your state's rules may apply to your situation.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "how-long-can-an-accident-claim-take",
    title: "How Long Can an Accident Claim Take?",
    category: "State Deadlines",
    excerpt: "Timelines vary widely. Understanding the factors that affect duration can help set expectations.",
    metaTitle: "How Long Can an Accident Claim Take?",
    metaDescription: "The factors that affect how long a personal injury claim may take, from medical recovery to negotiation and filing deadlines.",
    body: `## There is no single timeline\n\nSome claims resolve in a few months, while others take a year or more. The duration depends on the facts, the severity of injuries, and whether the case settles or proceeds to court.\n\n## Factors that affect duration\n\n- How long your treatment takes, since a claim is often valued after recovery reaches a stable point\n- The clarity of fault and the amount of evidence\n- The willingness of the insurer to negotiate reasonably\n- Court schedules if a lawsuit is filed\n\n## The statute of limitations\n\nEvery state sets a deadline, called the statute of limitations, by which a lawsuit must be filed. These deadlines vary and missing them can prevent a claim entirely.\n\n## Why it matters to act promptly\n\nActing early preserves evidence, protects your filing deadline, and keeps options open. Waiting can make it harder to document what happened.\n\n> This article is general information and is not legal advice. Deadlines vary by state and circumstance.`,
  },
  {
    slug: "should-i-accept-an-early-insurance-settlement",
    title: "Should I Accept an Early Insurance Settlement?",
    category: "Insurance Claims",
    excerpt: "A fast offer can be tempting. Here is what to consider before accepting.",
    metaTitle: "Should I Accept an Early Insurance Settlement?",
    metaDescription: "What to consider before accepting an early insurance settlement offer after an accident.",
    body: `## Why early offers happen\n\nInsurers sometimes make offers soon after an accident, before the full extent of injuries is known. A quick resolution can be appealing, but it may not account for ongoing or future costs.\n\n## What an offer may not include\n\n- Future treatment that becomes necessary\n- Long-term effects of an injury\n- Lost earning capacity\n- Non-economic damages such as pain and suffering\n\n## Once accepted, it is usually final\n\nSettlement agreements typically release the insurer from further responsibility for the claim. Accepting an offer generally means you cannot seek more later, even if new issues arise.\n\n## Understanding the full picture first\n\nUnderstanding the complete scope of your injuries and costs before accepting can help you make an informed decision. A participating attorney can review an offer and explain what it may mean.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "what-documents-help-support-an-injury-claim",
    title: "What Documents May Help Support an Injury Claim?",
    category: "Evidence and Documentation",
    excerpt: "Strong documentation supports a clearer claim. Here is a practical list.",
    metaTitle: "Documents That May Help Support an Injury Claim",
    metaDescription: "A practical list of the documents and records that can help support a personal injury claim.",
    body: `## Accident-related documents\n\n- The police or incident report\n- Photos and videos from the scene\n- Witness contact information and statements\n\n## Medical records\n\n- Emergency room and hospital records\n- Treatment notes from doctors and therapists\n- Bills, receipts, and prescription records\n\n## Financial records\n\n- Pay stubs or statements showing time off work\n- Receipts for out-of-pocket costs related to the accident\n- Repair estimates and vehicle-related expenses\n\n## Your own account\n\n- A written summary of what happened\n- Notes on how the injury has affected your daily life\n\nKeeping these organized in one place makes it easier to understand and present the full picture of what happened and how it affected you.\n\n> This article is general information and is not legal advice.`,
  },
  {
    slug: "understanding-medical-bills-and-lost-wages",
    title: "Understanding Medical Bills and Lost Wages After an Accident",
    category: "Compensation Basics",
    excerpt: "Medical bills and lost income are often the largest economic losses after an accident. Here is how they fit into a claim.",
    metaTitle: "Understanding Medical Bills and Lost Wages After an Accident",
    metaDescription: "How medical bills and lost wages are treated in a personal injury claim and what to document.",
    body: `## Medical bills\n\nMedical expenses are generally considered economic damages. This can include emergency care, hospital stays, surgery, rehabilitation, medication, and ongoing treatment. Keep every bill and receipt.\n\n## Lost wages\n\nTime off work caused by the accident may be recoverable. Pay records, employer statements, and tax documents can help show the income you lost.\n\n## Future treatment and earning capacity\n\nIf you need future treatment or your ability to earn has been affected, these may also be relevant. Documenting these often requires medical or vocational input.\n\n## How they fit into a claim\n\nEconomic damages such as these often form the foundation of a claim. Non-economic damages, where available, are frequently considered in relation to the economic losses.\n\n> This article is general information and is not legal advice.`,
  },
];

export const HOME_FAQ = [
  { q: "Is Accident Compensation Helper a law firm?", a: "No. Accident Compensation Helper is not a law firm and does not provide legal advice. If you choose to request contact, your information may be shared with participating attorneys or legal service providers who may review your situation." },
  { q: "Does using the claim check create an attorney-client relationship?", a: "No. Using this website does not create an attorney-client relationship. Any representation, fee agreement, and attorney-client relationship are established only through a separate agreement between you and an attorney." },
  { q: "How much does the claim check cost?", a: "The claim check is free to use. There is no charge and no obligation to request contact with a participating attorney." },
  { q: "How long does the claim check take?", a: "Most people complete the claim check in about two minutes. You can stop at any time, and your answers are used only to provide an informational assessment." },
  { q: "Is my information secure?", a: "Your information is handled securely and used to provide the claim check and, if you consent, to help connect you with participating providers. See our Privacy Policy for details." },
  { q: "What does the result mean?", a: "The result is an informational assessment based on the answers you provide. It is not a legal opinion, a settlement offer, or a guarantee of any outcome. A participating attorney must independently review your situation." },
  { q: "Am I obligated to hire an attorney?", a: "No. Choosing whether to request contact is entirely up to you. There is no obligation to hire an attorney, and many personal injury attorneys offer contingency-fee arrangements that you can confirm directly with them." },
  { q: "What if I was partly at fault?", a: "Many states apply comparative-fault rules that may reduce, but not always eliminate, what you may recover. How this applies depends on your state and the facts of your situation." },
];

export const COMPENSATION_CATEGORIES = [
  { title: "Medical expenses", desc: "Emergency care, hospital stays, surgery, medication, and ongoing treatment related to the accident." },
  { title: "Future treatment needs", desc: "Care that may be needed going forward, such as rehabilitation or follow-up procedures." },
  { title: "Lost income", desc: "Wages lost due to time off work caused by the accident and injuries." },
  { title: "Reduced earning capacity", desc: "Long-term effects on your ability to earn, where supported by the facts." },
  { title: "Property damage", desc: "Repair or replacement of a vehicle or other damaged property." },
  { title: "Pain and suffering", desc: "Non-economic damages for physical pain and emotional effects, where legally available." },
  { title: "Rehabilitation and support costs", desc: "Physical therapy, assistive devices, and related support needs." },
  { title: "Other accident-related losses", desc: "Additional losses that are connected to the accident and supported by the facts." },
];

export const HOW_IT_WORKS = [
  { step: 1, title: "Tell us what happened", desc: "Answer a short series of questions about the accident, injuries, treatment, location, and timing." },
  { step: 2, title: "Review your claim-check result", desc: "We use your answers to provide an informational assessment of whether your situation may warrant further review. This is not a legal opinion or guarantee." },
  { step: 3, title: "Choose whether to request contact", desc: "If your answers suggest a conversation may be useful, you can consent to be contacted by Accident Compensation Helper and participating providers." },
  { step: 4, title: "Speak directly with a participating attorney", desc: "Any legal advice, representation, fee agreement, or attorney-client relationship is handled directly between you and the attorney." },
];

export const WHY_USE = [
  "Start online at any time",
  "Complete the initial check in approximately two minutes",
  "Organise the important accident details",
  "Understand whether further review may be useful",
  "Choose whether to request contact",
  "No charge for using the claim-check tool",
  "No obligation to hire an attorney",
  "Clear disclosures before information is submitted",
];

export const TRUST_STRIP = [
  "Free claim check",
  "No obligation",
  "Secure submission",
  "Not a law firm",
  "No attorney-client relationship is created by using this website",
];