import React, { useEffect, useState } from "react";
import { FileText, Search } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { StatusPill, Loader, EmptyState } from "@/components/admin/AdminShared";
import { formatCurrency } from "@/lib/claimEngine";

export default function Claims() {
  const [claims, setClaims] = useState(null);
  const [query, setQuery] = useState("");

  useEffect(() => {
    base44.entities.ClaimEstimate.list("-created_date", 500)
      .then((r) => setClaims(r ?? []))
      .catch(() => setClaims([]));
  }, []);

  const filtered = (claims || []).filter((c) =>
    !query || `${c.first_name} ${c.last_name} ${c.email}`.toLowerCase().includes(query.toLowerCase())
  );

  if (claims === null) return <Loader />;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-heading text-3xl font-extrabold tracking-tight text-foreground">Claim Estimates</h1>
        <p className="mt-1 text-muted-foreground">Every estimate generated by the claim engine, with full breakdown.</p>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search by name or email..."
          className="h-11 w-full rounded-xl border border-input bg-card pl-10 pr-4 text-sm outline-none focus:ring-2 focus:ring-primary"
        />
      </div>

      {filtered.length === 0 ? (
        <EmptyState icon={FileText} title="No estimates yet" desc="Completed claim checks will show their estimates here." />
      ) : (
        <div className="overflow-x-auto rounded-2xl border border-border bg-card shadow-lift">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-secondary/40 text-left text-xs uppercase tracking-wider text-muted-foreground">
                <th className="px-5 py-3 font-medium">Claimant</th>
                <th className="px-5 py-3 font-medium">Type</th>
                <th className="px-5 py-3 font-medium">Injury</th>
                <th className="px-5 py-3 text-right font-medium">Economic</th>
                <th className="px-5 py-3 text-right font-medium">Range</th>
                <th className="px-5 py-3 text-right font-medium">With attorney</th>
                <th className="px-5 py-3 font-medium">Status</th>
                <th className="px-5 py-3 font-medium">Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {filtered.map((c) => (
                <tr key={c.id} className="transition-colors hover:bg-secondary/40">
                  <td className="px-5 py-3.5">
                    <p className="font-medium text-foreground">{c.first_name} {c.last_name}</p>
                    <p className="text-xs text-muted-foreground">{c.email || "-"}</p>
                  </td>
                  <td className="px-5 py-3.5 text-muted-foreground">{c.accident_type || "-"}</td>
                  <td className="px-5 py-3.5 text-muted-foreground">{c.injury_tier || "-"}</td>
                  <td className="px-5 py-3.5 text-right tabular-nums text-foreground">{formatCurrency(c.economic_damages || 0)}</td>
                  <td className="px-5 py-3.5 text-right tabular-nums text-foreground">{formatCurrency(c.range_low || 0)} - {formatCurrency(c.range_high || 0)}</td>
                  <td className="px-5 py-3.5 text-right tabular-nums font-semibold text-primary">{formatCurrency(c.represented_low || 0)} - {formatCurrency(c.represented_high || 0)}</td>
                  <td className="px-5 py-3.5"><StatusPill status={c.status} /></td>
                  <td className="px-5 py-3.5 text-muted-foreground">{new Date(c.created_date).toLocaleDateString("en-US")}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}